"""
agents/state.py

Defines the shared state TypedDict that flows through every node of the
GoodJob LangGraph pipeline.  Every field is optional (can be None) so that
nodes can be composed freely without requiring earlier nodes to have run.
"""

from __future__ import annotations

from typing import Any, Optional
from typing_extensions import TypedDict


class GoodJobState(TypedDict, total=False):
    """
    Shared state for the GoodJob agent graph.

    Field lifecycle
    ---------------
    1. ``company_name`` / ``job_posting_raw``
       Set by the caller before invoking the graph (or populated by the
       company-search / image-parser helpers).

    2. ``job_requirements``
       Populated by ``job_parser_node`` after analysing ``job_posting_raw``.

    3. ``user_profile_text``
       Loaded from the RAG vector store or set directly by the caller.

    4. ``retrieved_experiences``
       Filled by ``rag_retriever_node`` with the top-k profile chunks
       most relevant to ``job_requirements``.

    5. ``fit_score`` / ``fit_feedback``
       Computed by ``fit_analyzer_node``.  If ``fit_score < 0.3`` the
       graph ends early; otherwise it proceeds to ``resume_writer_node``.

    6. ``resume_draft``
       Written by ``resume_writer_node``.

    7. ``resume_final``
       The polished resume produced by ``reviewer_node``.

    8. ``messages``
       Append-only log of LangChain / LangGraph messages for debugging.

    9. ``current_step``
       Human-readable name of the currently executing node.

    10. ``errors``
        Accumulated non-fatal error strings from any node.
    """

    # ------------------------------------------------------------------ #
    # Input fields                                                         #
    # ------------------------------------------------------------------ #
    company_name: Optional[str]
    """Name of the target company (e.g. 'Kakao', 'Naver')."""

    job_posting_raw: Optional[str]
    """Full raw text of the job posting, scraped or pasted by the user."""

    # ------------------------------------------------------------------ #
    # Parsed job requirements (populated by job_parser_node)              #
    # ------------------------------------------------------------------ #
    job_requirements: Optional[dict[str, Any]]
    """
    Structured extraction of the job posting.  Expected keys:

    - ``required_skills``    : list[str]
    - ``preferred_skills``   : list[str]
    - ``experience_years``   : int | None
    - ``responsibilities``   : list[str]
    - ``company_culture``    : str
    """

    # ------------------------------------------------------------------ #
    # User profile                                                         #
    # ------------------------------------------------------------------ #
    user_profile_text: Optional[str]
    """Raw concatenated text of the user's profile / resume."""

    retrieved_experiences: Optional[list[str]]
    """Top-k relevant experience chunks returned by the RAG retriever."""

    # ------------------------------------------------------------------ #
    # Fit analysis (populated by fit_analyzer_node)                       #
    # ------------------------------------------------------------------ #
    fit_score: Optional[float]
    """Overall fit score in the range [0.0, 1.0]."""

    fit_feedback: Optional[str]
    """Detailed gap-analysis text explaining the fit score."""

    matched_skills: Optional[list[str]]
    """공고 필수/우대 기술 중 경험에서 근거가 확인된 기술."""

    missing_skills: Optional[list[str]]
    """공고 필수/우대 기술 중 경험에서 근거를 찾지 못한 기술."""

    # ------------------------------------------------------------------ #
    # Resume generation                                                    #
    # ------------------------------------------------------------------ #
    resume_draft: Optional[str]
    """Initial resume draft generated by resume_writer_node."""

    resume_final: Optional[str]
    """Polished, reviewer-approved resume."""

    # ------------------------------------------------------------------ #
    # Interview coaching (populated by interview_coach_node)              #
    # ------------------------------------------------------------------ #
    generate_interview: Optional[bool]
    """False 면 interview_coach 노드를 건너뜀 (기본 True)."""

    interview_questions: Optional[list[dict]]
    """
    면접 예상 질문 목록. 각 항목:
    - question  : 질문
    - intent    : 면접관의 질문 의도
    - category  : 기술 / 경험 / 컬처핏 / 약점 보완
    - answer_tip: 답변 전략 힌트
    """

    # ------------------------------------------------------------------ #
    # Meta / debugging                                                     #
    # ------------------------------------------------------------------ #
    messages: Optional[list[Any]]
    """Accumulated LangChain message objects (HumanMessage, AIMessage …)."""

    current_step: Optional[str]
    """Name of the node that is currently executing."""

    errors: Optional[list[str]]
    """Non-fatal errors collected during the run."""

    # ------------------------------------------------------------------ #
    # Job recommendation (populated by job_recommender_node)              #
    # ------------------------------------------------------------------ #
    recommendation_query: Optional[str]
    """키워드 or 직무명 (예: 'Python 백엔드', 'AI 엔지니어'). 비어 있으면 프로필에서 검색어를 뽑음."""

    recommendation_queries: Optional[list[str]]
    """실제로 검색에 쓴 검색어 목록 (직접 입력이면 1개, 프로필 기반이면 최대 3개)."""

    job_candidates: Optional[list[dict]]
    """
    수집된 공고 후보 목록. 각 항목:
    - raw_text      : 원문 텍스트
    - title         : 공고 제목
    - company       : 회사명
    - url           : 출처 URL
    - requirements  : JobRequirements.model_dump() 구조화 결과
    """

    ranked_matches: Optional[list[dict]]
    """
    fit_score 기준 내림차순 정렬된 매칭 결과 목록. 각 항목:
    - rank          : 순위 (1~N)
    - company       : 회사명
    - title         : 공고 제목
    - url           : 출처 URL
    - fit_score     : 0.0~1.0
    - fit_feedback  : 간략 분석
    - requirements  : 구조화된 요구사항
    """
